/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "git-2026-08-28-2de06e0fcc"
#endif /* AVUTIL_FFVERSION_H */
